### ISSUE TITLE
Integrate HAPI FHIR Server

### ISSUE THREAD

**Issue by n-krueger** [FHIR-Vaccination-Pass/vaccination-pass-server#3]
[HAPI FHIR](https://hapifhir.io/) is an open-source implementation of the FHIR resource server API written in Java and using Spring and JPA. By integrating the docker container provided by the project in our stack we gain instant access to data storage and querying capabilities for FHIR resources.

**Comment by ValiHar** [comment]
What is the HAPI FHIR JPA Server? Can you elaborate in the description?

**Comment by n-krueger** [comment]
@ValiHar done.
